### ISSUE TITLE
It has crash sometimes when uploading files

### ISSUE THREAD

**Issue by youngliangzhang** [filestack/filestack-java#62] opened 2018-06-14 20:24 UTC
Here is the log:
io.reactivex.exceptions.UndeliverableException: java.io.IOException
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:271)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:75)
        at io.reactivex.Flowable.subscribe(Flowable.java:13041)
        at io.reactivex.Flowable.subscribe(Flowable.java:12987)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException
        at com.filestack.internal.Upload.reduceChunkSize(Upload.java:113)
        at com.filestack.internal.UploadTransferFunc$2.onNetworkFail(UploadTransferFunc.java:108)
        at com.filestack.internal.RetryNetworkFunc.run(RetryNetworkFunc.java:53)
        at com.filestack.internal.RetryNetworkFunc.call(RetryNetworkFunc.java:36)
        at com.filestack.internal.UploadTransferFunc.uploadToS3(UploadTransferFunc.java:124)
        at com.filestack.internal.UploadTransferFunc.subscribe(UploadTransferFunc.java:41)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
        at io.reactivex.Flowable.subscribe(Flowable.java:13041)
        at io.reactivex.Flowable.subscribe(Flowable.java:12987)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by shawnmaten** [comment] 2018-06-14 21:47
That stacktrace is a bit confusing but I'm seeing:
```
Caused by: java.io.IOException
at com.filestack.internal.Upload.reduceChunkSize(Upload.java:113)
```
So you're running an "intelligent" upload and it's finally throwing an exception once it's reduced the part size past the minimum allowed for "intelligent" uploads. What kind of internet connection are you running this on when it throws the exception?

**Comment by youngliangzhang** [comment] 2018-06-14 22:00
I am not sure for internet connection because I got this log from Crash report service. This issue was happened on user's device.

**Comment by shawnmaten** [comment] 2018-06-15 16:11
The code is intended to throw an exception if uploading a part of the smallest size fails over 5 times. So if that's what's happening for this user, then it's working as intended, and you should handle the exception. If you can reproduce the exception in conditions where it doesn't seem reasonable to fail this way, then maybe there's a bug in the upload code. It's possible there's a bug in the upload code, but with this info, I assume the user is just experiencing a bad or unavailable network connection.

**Comment by shawnmaten** [comment] 2018-06-15 16:15
And by "bad network connection" I mean the connection is so bad we can't complete 32 KiB uploads.

**Comment by youngliangzhang** [comment] 2018-06-15 16:20
I see. Thanks for your information

**Comment by scana** [comment] 2018-09-28 14:49
Errors like this one will be replaced with more meaningful names in `1.0.0` release.
Closing for now.

**Closed by scana** 2018-09-28 14:49 UTC
